---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 2m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/texasbobs/k3s-lab-cluster
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: gatekeeper
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./gatekeeper
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: system-upgrade
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./system-upgrade
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: consrtaints
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./constraints
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: none
  
