---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: constrainttemplates
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./constrainttemplates
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
