---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: system-upgrade
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./system-upgrade
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: none