apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

#Use this to build a file with all of the constraint templates 

#Include the entire library
#- github.com/open-policy-agent/gatekeeper-library/library

#Include specific constraints
- github.com/open-policy-agent/gatekeeper-library/library/general/containerlimits

# You can optionally install a subset by specifying a subfolder, or specify a commit SHA
# - github.com/open-policy-agent/gatekeeper-library/library/pod-security-policy?ref=0c82f402fb3594097a90d15215ae223267f5b955

# Add custom constraints here
# - constraints.yaml
